# -*- coding: utf-8 -*-
"""Decodelab Wk 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qRFQZbu4l0qkCIfPLNf9S6ZGfV-RACMb
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import sklearn
from statsmodels.formula.api import ols
# %matplotlib inline
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

import pandas as pd
import numpy as np

"""### Load Dataset

We'll load the provided Excel file `New Dataset.xlsx` into a pandas DataFrame.
"""

file_path = '/content/New Dataset.xlsx'
df = pd.read_excel(file_path)
display(df.head())

"""### Initial Data Exploration

Let's get a quick overview of the dataset's structure, data types, and summary statistics.
"""

print("DataFrame Info:")
df.info()

print("\nDescriptive Statistics:")
display(df.describe(include='all'))

print("\nMissing Values:")
display(df.isnull().sum().to_frame(name='Missing Count'))

print("\nUnique Values per Column:")
display(df.nunique().to_frame(name='Unique Count'))

"""### Distribution of TotalPrice

Let's visualize the distribution of the `TotalPrice` column using a histogram.
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['TotalPrice'], bins=30, kde=True)
plt.title('Distribution of Total Price')
plt.xlabel('Total Price')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)
plt.show()

"""### Outlier Detection for TotalPrice

Let's use a boxplot to identify potential outliers in the `TotalPrice` column.
"""

plt.figure(figsize=(10, 6))
sns.boxplot(y=df['TotalPrice'])
plt.title('Boxplot of Total Price to Identify Outliers')
plt.ylabel('Total Price')
plt.grid(axis='y', alpha=0.75)
plt.show()

"""### Quantifying Outliers: Mean and Median of TotalPrice

Let's calculate the mean and median of the `TotalPrice` to understand its central tendency and the impact of outliers.
"""

mean_total_price = df['TotalPrice'].mean()
median_total_price = df['TotalPrice'].median()

print(f"Mean of TotalPrice: {mean_total_price:.2f}")
print(f"Median of TotalPrice: {median_total_price:.2f}")

"""### Filter by 95th Percentile of TotalPrice

Let's identify and display rows where `TotalPrice` is greater than its 95th percentile to focus on high-value transactions or potential outliers.
"""

percentile_95 = df['TotalPrice'].quantile(0.95)
print(f"95th Percentile of TotalPrice: {percentile_95:.2f}")

df_high_total_price = df[df['TotalPrice'] > percentile_95]
print(f"\nNumber of rows with TotalPrice > 95th percentile: {len(df_high_total_price)}")
display(df_high_total_price.head())

"""### High-Value Products Analysis

Now, let's group the `df_high_total_price` DataFrame by the 'Product' column to see which items appear most frequently in these high-value orders.
"""

high_value_products = df_high_total_price['Product'].value_counts().reset_index()
high_value_products.columns = ['Product', 'Count']

print("Products frequently appearing in high-value orders:")
display(high_value_products)

"""### Visualization of High-Value Products

Let's visualize the frequency of products appearing in high-value orders using a bar chart.
"""

plt.figure(figsize=(12, 7))
sns.barplot(x='Product', y='Count', data=high_value_products, palette='viridis')
plt.title('Frequency of Products in High-Value Orders')
plt.xlabel('Product')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', alpha=0.75)
plt.tight_layout()
plt.show()

"""### Purchase Trends Over Time for Top High-Value Products

Let's analyze how the sales of our top high-value products have trended over time.
"""

# Get the list of top high-value products
top_products_list = high_value_products['Product'].tolist()
print(f"Top high-value products: {top_products_list}")

# Filter the original DataFrame for these top products
df_top_products_trends = df[df['Product'].isin(top_products_list)].copy()

# Aggregate total sales for each top product by date
product_daily_sales = df_top_products_trends.groupby(['Date', 'Product'])['TotalPrice'].sum().reset_index()

display(product_daily_sales.head())

plt.figure(figsize=(15, 8))
sns.lineplot(x='Date', y='TotalPrice', hue='Product', data=product_daily_sales, marker='o')
plt.title('Daily Total Price Trend for Top High-Value Products')
plt.xlabel('Date')
plt.ylabel('Total Price')
plt.xticks(rotation=45, ha='right')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(title='Product')
plt.tight_layout()
plt.show()